### ISSUE TITLE
Enable use of <svelte:head> without client bundle

### ISSUE THREAD

**Issue by arggh** [gobeli/eleventy-plugin-svelte#6]
Thanks for building this plugin.

Unless I missed something, it currently seems that anything declared in the page-components' _(for example index.11ty.svelte)_  `<svelte:head>` block doesn't get included in the rendered html.

I think it would be an important improvement, since Eleventy is all about being a static site generator.

**Comment by gobeli** [comment]
You're right, I'll look into that!
