### ISSUE TITLE
Error rendering markdown

### ISSUE THREAD

**Issue by nemo-omen** [gobeli/eleventy-plugin-svelte#7]
Is there some configuration I need to set to keep rendering markdown files with this plugin installed? I'm trying to add this to a project and I keep getting the following for any markdown files:

`Template render error was thrown
> "src/posts/hello.md" is not a valid Svelte template.`

**Comment by gobeli** [comment]
Unfortunately I can't reproduce that error, what does your `eleventyConfig` look like?

**Comment by nemo-omen** [comment]
Here it is (I have to admit to not knowing much about configuring either eleventy or rollup):
`const syntaxHighlight = require('@11ty/eleventy-plugin-syntaxhighlight');
const markdownIt = require('markdown-it');
const markDownItClass = require('@toycode/markdown-it-class');
const EleventySvelte = require('eleventy-plugin-svelte');
const postcss = require('rollup-plugin-postcss');
const terser = require('rollup-plugin-terser').terser;

const dev = process.env.NODE_ENV === 'development'

const md = markdownIt({linkify: true, html: true});

module.exports = function (eleventyConfig) {
    eleventyConfig.addWatchTarget("./_tmp/style.css");
    eleventyConfig.addPassthroughCopy({ "./_tmp/style.css": "./css/style.css" });
    eleventyConfig.addPassthroughCopy('src/css');
    eleventyConfig.addPassthroughCopy('src/js');
    eleventyConfig.addPassthroughCopy('src/img');
    eleventyConfig.addPlugin(syntaxHighlight);

    eleventyConfig.addPlugin(EleventySvelte, {
        rollupPluginSvelteSSROptions: {
            dev,
        },
        rollupPluginSvelteClientOptions: {
            dev,
            emitCss: true,
        },
        rollupClientPlugins: [postcss(), !dev && terser()],
    });

    eleventyConfig.addShortcode("version", function () {
        return String(Date.now());
      });

    return {
        dir: {
            input: 'src',
            // templateFormats: ['md', 'njk', 'svelte']
            // includes: 'includes',
            // layouts: 'layouts'
        },
        passthroughFileCopy: true
    }
}`

**Comment by nemo-omen** [comment]
It looks like it's happening when I try to specify the `main.njk` layout in the frontmatter of the md file. when I leave it out it processes the md file with no layout.

I've tried specifying a `11ty.svelte` file as a layout for the markdown, which I know is not a feature, but it does process the layout file with no templateContent data. So ... I'm guessing I need to figure out how to access `templateContent`.

**Comment by nemo-omen** [comment]
Oh, hey, it's right there on `data._templateContent`!

I think I just misunderstood how to specify templates for markdown files. As long as I provide a `11ty.svelte` file for the markdown template I should be able to access all of the template's data.

**Comment by gobeli** [comment]
Oh I could reproduce it now. You shouldn't have to jump through all these hoops to get there. The problem is, that the shortcode to load the svelte client tries to find the component but obviously can't find one for the `md` file. I'll publish a fix!

**Comment by gobeli** [comment]
The fix is up in version `1.0.4`
